# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillKeywords',
            new_name='SkillKeyword',
        ),
        migrations.AlterModelOptions(
            name='basics',
            options={'verbose_name_plural': 'Basics'},
        ),
    ]
