# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20160503_0748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterestKeywords',
            new_name='InterestKeyword',
        ),
    ]
