# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20160503_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Education'},
        ),
        migrations.AlterField(
            model_name='basics',
            name='summary',
            field=models.TextField(),
        ),
    ]
