# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20160503_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basics',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='basics',
            name='address2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basics',
            name='postalCode',
            field=models.CharField(max_length=255, verbose_name='post code'),
        ),
        migrations.AlterField(
            model_name='basics',
            name='region',
            field=models.CharField(max_length=255, verbose_name='State/Province'),
        ),
    ]
