# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20160503_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basics',
            name='address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='basics',
            name='countryCode',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
