# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20160503_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='area',
            new_name='degreeType',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='education',
            name='studyType',
        ),
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='award',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='basics',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='basics',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='basics',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='job',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
