# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20160506_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basics',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
