# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20160506_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
