# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20160506_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.TextField(max_length=255)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Education')),
            ],
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name_plural': 'Volunteering'},
        ),
    ]
