# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-23 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_auto_20160704_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationhighlight',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='resume.Education'),
        ),
        migrations.AlterField(
            model_name='jobhighlight',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='resume.Job'),
        ),
        migrations.AlterField(
            model_name='volunteerhighlight',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='resume.Volunteer'),
        ),
    ]
