# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-23 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_auto_20160722_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='endDatePrecision',
            field=models.CharField(choices=[('d', 'Day'), ('m', 'Month'), ('y', 'Year')], default='y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='startDatePrecision',
            field=models.CharField(choices=[('d', 'Day'), ('m', 'Month'), ('y', 'Year')], default='y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='endDatePrecision',
            field=models.CharField(choices=[('d', 'Day'), ('m', 'Month'), ('y', 'Year')], default='y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='startDatePrecision',
            field=models.CharField(choices=[('d', 'Day'), ('m', 'Month'), ('y', 'Year')], default='y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='endDatePrecision',
            field=models.CharField(choices=[('d', 'Day'), ('m', 'Month'), ('y', 'Year')], default='y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='startDatePrecision',
            field=models.CharField(choices=[('d', 'Day'), ('m', 'Month'), ('y', 'Year')], default='y', max_length=1),
            preserve_default=False,
        ),
    ]
