# Generated by Django 3.2.6 on 2021-11-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_auto_20160912_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='endDate',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='endDatePrecision',
            field=models.CharField(blank=True, choices=[('d', 'Day'), ('m', 'Month'), ('y', 'Year')], max_length=1, null=True),
        ),
    ]
