# Generated by Django 3.2.6 on 2021-11-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_skill_skill_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='sort_order',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
