# Generated by Django 3.2.6 on 2021-11-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_skill_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='sort_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('skill_group', 'sort_order')},
        ),
    ]
